In [2]:
import joblib
import pandas as pd

In [3]:
model = joblib.load("employee_recommendation_model.pkl")

In [4]:
print("Number of Features:", len(model.feature_names_in_))
print(model.feature_names_in_)

Number of Features: 65
['experience_years' 'workload_percentage' 'active_tasks'
 'performance_score' 'estimated_hours' 'hours_logged'
 'progress_percentage' 'allocation_score' 'skill_match'
 'skill_computer_vision' 'skill_data_analysis' 'skill_deep_learning'
 'skill_django' 'skill_excel' 'skill_finance' 'skill_machine_learning'
 'skill_nlp' 'skill_project_management' 'skill_python' 'skill_react'
 'skill_sql' 'department_Data Science' 'department_Engineering'
 'department_Finance' 'department_HR' 'department_IT'
 'department_Marketing' 'department_Operations' 'department_Sales'
 'job_role_Analyst' 'job_role_Business Analyst' 'job_role_Data Scientist'
 'job_role_Developer' 'job_role_Finance Analyst' 'job_role_HR Executive'
 'job_role_Project Manager' 'job_role_Senior Developer'
 'job_role_Team Lead' 'availability_status_Available'
 'availability_status_Busy' 'availability_status_On Leave'
 'availability_status_Unknown' 'task_priority_Critical'
 'task_priority_High' 'task_priority_Low' 'task_priority_Medium'
 'task_priority_Unknown' 'task_status_Blocked' 'task_status_Completed'
 'task_status_In Progress' 'task_status_Not Started' 'task_status_Unknown'
 'required_skill_Computer Vision' 'required_skill_Data Analysis'
 'required_skill_Deep Learning' 'required_skill_Django'
 'required_skill_Excel' 'required_skill_Finance'
 'required_skill_Machine Learning' 'required_skill_NLP'
 'required_skill_Project Management' 'required_skill_Python'
 'required_skill_React' 'required_skill_SQL' 'required_skill_Unknown']

In [5]:
df = pd.read_csv("Business_Operation_ml_ready.csv")

print(df.shape)
df.head()

(50000, 67)

,employee_id,experience_years,workload_percentage,active_tasks,performance_score,estimated_hours,hours_logged,progress_percentage,allocation_score,recommended_employee,...,required_skill_Django,required_skill_Excel,required_skill_Finance,required_skill_Machine Learning,required_skill_NLP,required_skill_Project Management,required_skill_Python,required_skill_React,required_skill_SQL,required_skill_Unknown
0,EMP2373,4.1,27.0,2,71.9,36.5,25.1,76.8,16.5,1,...,False,False,False,False,False,False,False,False,False,False
1,EMP4021,6.1,100.0,8,75.0,44.4,21.9,56.9,43.8,1,...,False,False,False,False,True,False,False,False,False,False
2,EMP2457,2.1,67.9,2,62.2,32.0,21.2,56.6,41.9,1,...,False,False,False,False,False,True,False,False,False,False
3,EMP2344,4.5,47.5,3,72.7,43.1,40.4,96.7,22.5,0,...,False,False,False,True,False,False,False,False,False,False
4,EMP205,13.6,49.3,2,77.0,33.5,29.4,92.8,49.2,1,...,False,False,True,False,False,False,False,False,False,False

In [6]:
print(df.columns.tolist())

['employee_id', 'experience_years', 'workload_percentage', 'active_tasks', 'performance_score', 'estimated_hours', 'hours_logged', 'progress_percentage', 'allocation_score', 'recommended_employee', 'skill_match', 'skill_computer_vision', 'skill_data_analysis', 'skill_deep_learning', 'skill_django', 'skill_excel', 'skill_finance', 'skill_machine_learning', 'skill_nlp', 'skill_project_management', 'skill_python', 'skill_react', 'skill_sql', 'department_Data Science', 'department_Engineering', 'department_Finance', 'department_HR', 'department_IT', 'department_Marketing', 'department_Operations', 'department_Sales', 'job_role_Analyst', 'job_role_Business Analyst', 'job_role_Data Scientist', 'job_role_Developer', 'job_role_Finance Analyst', 'job_role_HR Executive', 'job_role_Project Manager', 'job_role_Senior Developer', 'job_role_Team Lead', 'availability_status_Available', 'availability_status_Busy', 'availability_status_On Leave', 'availability_status_Unknown', 'task_priority_Critical', 'task_priority_High', 'task_priority_Low', 'task_priority_Medium', 'task_priority_Unknown', 'task_status_Blocked', 'task_status_Completed', 'task_status_In Progress', 'task_status_Not Started', 'task_status_Unknown', 'required_skill_Computer Vision', 'required_skill_Data Analysis', 'required_skill_Deep Learning', 'required_skill_Django', 'required_skill_Excel', 'required_skill_Finance', 'required_skill_Machine Learning', 'required_skill_NLP', 'required_skill_Project Management', 'required_skill_Python', 'required_skill_React', 'required_skill_SQL', 'required_skill_Unknown']

In [9]:
employee = df.iloc[[0]].copy()

employee = employee.drop(
    columns=["employee_id", "recommended_employee"]
)

In [10]:
prediction = model.predict(employee)

print("Prediction:", prediction)

Prediction: [1]

In [11]:
prediction = model.predict(employee)[0]

if prediction == 1:
    print("Employee Recommended")
else:
    print("Employee Not Recommended")

Employee Recommended

In [12]:
prob = model.predict_proba(employee)

print("Not Recommended Probability:", prob[0][0])
print("Recommended Probability:", prob[0][1])

Not Recommended Probability: 0.12
Recommended Probability: 0.88

In [13]:
employee = df.iloc[[0]].copy()

print("Employee ID:", df.iloc[0]["employee_id"])
print("Experience:", df.iloc[0]["experience_years"])
print("Performance Score:", df.iloc[0]["performance_score"])
print("Workload:", df.iloc[0]["workload_percentage"])

Employee ID: EMP2373
Experience: 4.1
Performance Score: 71.9
Workload: 27.0

In [17]:
employee_input = employee.drop(
    columns=["employee_id", "recommended_employee"]
)
prediction = model.predict(employee_input)[0]

In [18]:
# Predict
prediction = model.predict(employee_input)[0]

if prediction == 1:
    print("Employee Recommended")
else:
    print("Employee Not Recommended")

Employee Recommended

In [21]:
def recommend_employee(row):

    emp = row.copy()

    emp = emp.drop(
        labels=["employee_id", "recommended_employee"]
    )

    emp_df = pd.DataFrame([emp])

    prediction = model.predict(emp_df)[0]

    probability = model.predict_proba(emp_df)[0][1]

    return prediction, probability

In [22]:
for i in range(5):

    employee = df.iloc[i]

    prediction, probability = recommend_employee(employee)

    print(
        employee["employee_id"],
        prediction,
        probability
    )

EMP2373 1 0.88
EMP4021 1 0.9
EMP2457 1 0.9
EMP2344 0 0.23
EMP205 1 0.89

In [23]:
# Top recommended employees

In [24]:
results = []

for i in range(len(df)):

    prediction, probability = recommend_employee(df.iloc[i])

    results.append([
        df.iloc[i]["employee_id"],
        prediction,
        probability
    ])

result_df = pd.DataFrame(
    results,
    columns=[
        "employee_id",
        "recommended",
        "probability"
    ]
)

In [25]:
top_employees = result_df.sort_values(
    by="probability",
    ascending=False
)

top_employees.head(10)

      employee_id  recommended  probability
38899     EMP1770            1          1.0
38144     EMP1600            1          1.0
17964     EMP2434            1          1.0
38067      EMP940            1          1.0
29261     EMP3188            1          1.0
38070      EMP348            1          1.0
29237     EMP4035            1          1.0
18021     EMP4901            1          1.0
48382      EMP944            1          1.0
46024     EMP1519            1          1.0

In [31]:
def get_best_employees(data, top_n=5):

    temp = []

    for i in range(len(data)):

        prediction, probability = recommend_employee(data.iloc[i])

        if prediction == 1:

            temp.append([
                data.iloc[i]["employee_id"],
                probability
            ])

    result = pd.DataFrame(
        temp,
        columns=["employee_id", "probability"]
    )

    return result.sort_values(
        by="probability",
        ascending=False
    ).head(top_n)

In [33]:
task = {
    "required_skill": "Python",
    "department": "Engineering",
    "priority": "High"
}

In [34]:
candidates = df[
    (df["required_skill_Python"] == 1) &
    (df["department_Engineering"] == 1)
]

In [35]:
get_best_employees(candidates, top_n=5)

    employee_id  probability
441     EMP4419          1.0
54      EMP3995          1.0
147     EMP4556          1.0
456     EMP4281          1.0
455     EMP1368          1.0

In [36]:
print("Number of candidates:", len(candidates))

Number of candidates: 787

In [37]:
candidates[[
    "employee_id",
    "experience_years",
    "workload_percentage",
    "active_tasks",
    "performance_score",
    "availability_status_Available"
]].head()

,employee_id,experience_years,workload_percentage,active_tasks,performance_score,availability_status_Available
21,EMP4271,9.7,100.0,1,78.1,True
27,EMP3693,2.6,73.2,7,63.9,True
149,EMP995,14.8,58.5,3,82.0,False
192,EMP680,7.5,47.8,5,69.2,True
498,EMP3215,9.7,31.0,1,72.6,False

In [38]:
recommended = get_best_employees(candidates, top_n=5)
recommended

    employee_id  probability
441     EMP4419          1.0
54      EMP3995          1.0
147     EMP4556          1.0
456     EMP4281          1.0
455     EMP1368          1.0

In [39]:
recommended_details = candidates[
    candidates["employee_id"].isin(recommended["employee_id"])
][[
    "employee_id",
    "experience_years",
    "workload_percentage",
    "active_tasks",
    "performance_score",
    "availability_status_Available"
]]

recommended_details

,employee_id,experience_years,workload_percentage,active_tasks,performance_score,availability_status_Available
4228,EMP4419,3.1,64.2,6,73.1,True
5000,EMP4419,3.1,64.2,4,73.1,True
5485,EMP3995,8.2,57.3,3,84.9,True
12708,EMP4556,5.2,70.5,4,60.0,True
12911,EMP4556,5.2,70.5,6,60.0,True
14117,EMP4419,3.1,64.2,2,73.1,True
19141,EMP1368,4.4,68.9,5,68.1,True
25751,EMP4419,3.1,64.2,4,73.1,True
30155,EMP3995,8.2,57.3,3,84.9,True
34842,EMP4281,4.4,45.8,3,64.2,True
36072,EMP4419,3.1,64.2,5,73.1,True
36979,EMP1368,4.4,68.9,5,68.1,True
37141,EMP4281,4.4,45.8,4,64.2,True
45193,EMP4419,3.1,64.2,4,73.1,True

In [40]:
recommended_details = (
    candidates[
        candidates["employee_id"].isin(recommended["employee_id"])
    ][[
        "employee_id",
        "experience_years",
        "workload_percentage",
        "active_tasks",
        "performance_score",
        "availability_status_Available"
    ]]
    .drop_duplicates(subset=["employee_id"])
)

recommended_details

,employee_id,experience_years,workload_percentage,active_tasks,performance_score,availability_status_Available
4228,EMP4419,3.1,64.2,6,73.1,True
5485,EMP3995,8.2,57.3,3,84.9,True
12708,EMP4556,5.2,70.5,4,60.0,True
19141,EMP1368,4.4,68.9,5,68.1,True
34842,EMP4281,4.4,45.8,3,64.2,True

In [41]:
recommended["probability"].describe()

count    5.0
mean     1.0
std      0.0
min      1.0
25%      1.0
50%      1.0
75%      1.0
max      1.0
Name: probability, dtype: float64

In [43]:
all_recommendations = get_best_employees(candidates, top_n=len(candidates))

all_recommendations["probability"].value_counts().head(20)

probability
0.95    39
0.99    39
0.98    37
0.97    35
0.92    32
0.89    29
0.91    28
1.00    27
0.96    27
0.94    27
0.87    25
0.90    21
0.93    21
0.84    19
0.85    16
0.86    15
0.88    14
0.83    12
0.80    12
0.82    11
Name: count, dtype: int64

In [44]:
recommended["probability"].unique()

array([1.])

In [45]:
import joblib

joblib.dump(model, "employee_recommendation_model.pkl")

['employee_recommendation_model.pkl']

In [46]:
from employee_recommendation import get_best_employees
import pandas as pd

In [47]:
df = pd.read_csv("Business_Operation_ml_ready.csv")

get_best_employees(df, top_n=5)

      employee_id  probability
31969     EMP2139          1.0
10836     EMP3132          1.0
31370     EMP4544          1.0
36462      EMP470          1.0
36464     EMP3547          1.0